### ISSUE TITLE
First toast is not animating into the screen

### ISSUE THREAD

**Issue by callum-veloxcommerce** [bmcmahen/toasted-notes#10]
I like this package, i am just having some strange behaviour when calling toast.notify.

From some components it is firing perfectly, and others the animation does not start and it is stuck above the screen.

The only difference between the components I can note is that one is a top level route, and one is a nested route.

**Comment by callum-veloxcommerce** [comment]
Additional testing has also highlighted that sometimes it works fine if called outside of an axios promise but not inside of one.

**Comment by bmcmahen** [comment]
Can you show me the code snippet you are using to call `toast.notify` from inside the axios promise?

**Comment by callum-veloxcommerce** [comment]
```

	render() {

		let _oldPassword, _newPassword, _confirmNewPassword;

		const changePassword = e =>
		{
			e.preventDefault();
			this._isMounted && this.setState({
				loading: true,
				changeButtonText: "Please wait...",
				changeButtonEnabled: false
			});

			if (e.currentTarget.checkValidity() === false) {
				event.stopPropagation();
				e.currentTarget.classList.add('was-validated');
				this.setState({
					loading: false,
					changeButtonText: "Change",
					changeButtonEnabled: true
				});
			} 
			else 
			{
				let repeatPasswordInput = document.getElementById('confirm_new_password');

				if(_newPassword.value !== _confirmNewPassword.value)
				{
					toast.notify('Please double check your passwords are the same');
					repeatPasswordInput.classList.add('is-invalid');

					if(repeatPasswordInput.classList.contains('is-valid'))
					{
						repeatPasswordInput.classList.remove('is-valid');
					}

					this.setState({
						registerButtonText: "Create account",
						registerButtonEnabled: true
					});
				} 
				else 
				{
					axios
					.put("http://local.webapp.mlc.co.uk/api/user/details/password",{
						'old_password': btoa(_oldPassword.value),
						'password': btoa(_newPassword.value),
					},{
						headers: {'Authorization': "Bearer " + store.getState().user.user.auth_token}
					})
					.then(response => {
						return response;
					})
					.then((json) => {

						if (json.data.success) {
									
							toast.notify('Your password was changed');
							this._isMounted && this.setState({
								loading: false,
								changeButtonText: "Change",
								changeButtonEnabled: true
							});
						}
					});
					e.target.reset();
					e.currentTarget.classList.remove('was-validated');
					if(repeatPasswordInput.classList.contains('is-invalid'))
					{
						repeatPasswordInput.classList.remove('is-invalid');
					}
				}
			}
		}
```

**Comment by bmcmahen** [comment]
Hmm, it's hard for me to say from just looking at that. FYI, it's better to hold form data (was-validated, values, etc.) in component state and render them that way, though I don't think this is necessarily related to the toast issue.

I'm afraid I can't help much without a reproducible example. I haven't run into these issues myself. Are you sure the `toast.notify` is actually being called?

**Comment by callum-veloxcommerce** [comment]
Hi, apologies for the messy snippet above, I have spent some time figuring out the issue. 

I am using a _isMounted property on my components due to having nested routing and ajax calls on mount. 

It turned out that all of the components that had correctly set _isMounted to true, in componentDidMount, the notifications worked fine. But when the _isMounted was not set to true then the first toast notification was staying hidden above the screen and not animating.

Have absolutely no idea why these things are conflicting though as they are not related in any way.

**Comment by bmcmahen** [comment]
Yeah, a bit weird. Hrm. Let me know if you have any other problems.
