### ISSUE TITLE
Rendering issue fixed by reverting to React Spring 8

### ISSUE THREAD

**Issue by scf4** [bmcmahen/toasted-notes#11]
Sometimes an alert isn't visible, until I hover over the space where it should be. I switched to the latest stable version of react spring `8.0.27` (rather than the 9 beta) and it seems to have gone away.

**Comment by bmcmahen** [comment]
Hmm, good to know. I'm basically only using v9 because of the typescript fixes. I think ideally I should make react-spring a peer dependency and advocate using v8.

**Comment by r1y4h** [comment]
@scf4 
How did you forced to use v8.0.27 of react-spring. I am having the same issue.

**Comment by scf4** [comment]
@r1y4h in package.json
<img width="313" alt="image" src="https://user-images.githubusercontent.com/768234/64015166-db945e00-cb1b-11e9-9624-10b21ee8f34a.png">

**Comment by r1y4h** [comment]
I downgraded to v2.1.5 which works too. But I think your solution is better and it does work as well.

**Comment by bmcmahen** [comment]
I've just published a new version which has `react-spring` as a peer dependency, so you should now be able to use v8 by installing it yourself. I think it ultimately makes more sense to list `react-spring` as a peer dependency anyway.
