### ISSUE TITLE
Possible to display only one instance of toaster

### ISSUE THREAD

**Issue by r1y4h** [bmcmahen/toasted-notes#12]
Is it possible to display only one instance of toaster?
I have a scenario where I use the toaster to prompt user for input and toaster will only be dismissed by user's action
A user may trigger another toaster but the previous should go away immediately.

Thanks

**Comment by bmcmahen** [comment]
hey @r1y4h  - this function doesn't really exist in the current component. It might be something I could add in the future. I'll mark it as a feature request.

**Comment by r1y4h** [comment]
hi @bmcmahen thanks. A quick solution can be to provide a public method to close all toasters

**Comment by bmcmahen** [comment]
Definitely. I'll try to get to this soon, or I'll happily accept a PR. It shouldn't be too difficult to implement.

**Comment by r1y4h** [comment]
hi @bmcmahen I see that internally you have a method to remove toasters and be possibly exposed to remove all. But the team decided to just use a modal instead as there are other issues when toasters are forced to use a prompt instead of just toasters.
