### ISSUE TITLE
Message Type Is Not Working

### ISSUE THREAD

**Issue by luna215** [bmcmahen/toasted-notes#6]
Specifying the type of message doesn't render a different message, but the same white message.

<img width="493" alt="Screen Shot 2019-05-02 at 12 48 19 PM" src="https://user-images.githubusercontent.com/7971405/57103452-a2b5bb00-6cda-11e9-9971-6668f0383fcc.png">

**Comment by bmcmahen** [comment]
Yeah, message type isn't actually supported in this library. You could use the version found in [sancho](https://github.com/bmcmahen/sancho/blob/master/src/Toast.tsx) for this. Or you can use the other render options to provide your own custom styling (see the implementation in Sancho for an example). 

Was the type option mentioned in the docs somewhere? I used to support it in an older version but thought it better to leave this to the user.

**Comment by luna215** [comment]
@bmcmahen no, I was just scavenging through the code and noticed their an options for message type.

**Comment by bmcmahen** [comment]
Ah, thanks. I should probably clear that up since it was supported in an older version, but isn't anymore.
