### ISSUE TITLE
Notifications ain't positioned correctly when several are fired at the same time

### ISSUE THREAD

**Issue by pashazz** [bmcmahen/toasted-notes#8]
NOTE: I use custom component with what appears to be a 'non-native' size there. I fired them at the same time

![image](https://user-images.githubusercontent.com/45922/57628119-fb6e3900-75a1-11e9-8d40-5071337aa908.png)

It could be reproduced w/any custom sized notification components

**Comment by bmcmahen** [comment]
Can you share the code you use to trigger them?

**Comment by pashazz** [comment]
[sure](https://github.com/ispras/vmemperor/blob/devil/frontend/app/components/Toast/taskComponent.tsx#L68).

Yeah, the thing is that data property might be null at first when data is not received yet

**Comment by bmcmahen** [comment]
Make sure you use a fixed height for your alert component and it should fix this.

Something like this: 

```jsx
<div style={{ height: '300px' }}>
        <Alert color={alertColor} toggle={onClose}>
          <h4 className="alert-heading">
            {data && data.nameLabel || defaultTitle || "Loading..."}
          </h4>
          <Progress value={data && data.progress * 100 || 0}>

          </Progress>
          <hr/>
          {data && data.errorInfo.map(string => (
            <Label>{string}</Label>
          ))}
        </Alert>
      </div>
```
